services:
  - type: web
    name: disease-predictor-low
    plan: free
    env: docker
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
